### ISSUE TITLE
deploy processing hub on VM

### ISSUE THREAD

**Issue by jdegerickx** [WorldCereal/worldcereal-vdm#15]
To deploy the production version of the new "Processing Hub" application, we need to determine the domain on which it will be accessible and the VM on which it will be deployed. We can deploy it on the same VM as VDM.

As a separate application, it will need to be accessible via its own domain. We will also add a new card for it on the VDM homepage, allowing access from VDM. Could you please create a new subdomain for the "Processing Hub," similar to the one for VDM? If we agree to deploy it next to VDM, please point the new domain to the VDM VM. It will also be necessary to configure the CDSE OAuth system to accept the Processing Hub on the new domain, as was done for the DEV version.

If this is not possible before the webinar, we can present the Processing Hub from the dev version hosted on our infrastructure.

**Comment by soxofaan** [comment]
As discussed in chat: I was not really involved with setting up the VM or configuring domains for this, so I'm not sure I'm well equipped to tackle this issue at the moment.


I can help with

> configure the CDSE OAuth system to accept the Processing Hub on the new domain

but for that I need to know what the actual domain(s) will be

**Comment by jdegerickx** [comment]
@kvantricht, ok to assign "prhub.esa-worldcereal.org" as the domain name for the Processing Hub application?
(just to keep it short)
alternative could be: "processing.esa-worldcereal.org"

**Comment by kvantricht** [comment]
Why not just “hub”?

**Comment by jdegerickx** [comment]
also fine, maybe a bit less self-explanatory, but I guess "prhub" isn't either :)

**Comment by kvantricht** [comment]
prhub sounds more like the place to host news items and socials. How urgent is this? Can it wait till Monday?

**Comment by soxofaan** [comment]
"prhub"  may also cause undesired effects in contexts with autocorrect/autosuggest features  😉

**Comment by jdegerickx** [comment]
of course it can wait till Monday...

**Comment by kvantricht** [comment]
Options I think are nice:
- hub.esa-worldcereal.org
- engine.esa-worldcereal.org
- compute.esa-worldcereal.org
- ops.esa-worldcereal.org

**UPDATE: we chose hub.esa-worldcereal.org**

**Comment by soxofaan** [comment]
FYI: Keycloak/CDSE auth config for `hub.esa-worldcereal.org` should be in place now (internal ref: CDSE-1885)

**Comment by mbabic84** [comment]
Hi @soxofaan could you please check CDSE keycloak configuration. Getting the following error message

![Image](https://github.com/user-attachments/assets/5a46d08d-e4e0-41e4-83d3-98db4af987a6)

Thank you.

**Comment by mbabic84** [comment]
Hi all,

there is some issue with login to CDSE on production instance. Could you
please check it.

https://github.com/WorldCereal/worldcereal-vdm/issues/15#issuecomment-2734149815

Thank you,

Martin

**Comment by soxofaan** [comment]
What redirect URI is being used in this example?
Note that I don't have direct access to the CDSE keycloak configuration, I need enough information to raise an actionable question towards the people that do have access

**Comment by kvantricht** [comment]
Note that this afternoon it's the webinar. Does the above error affect the processing hub's default usage by users?

**Comment by mbabic84** [comment]
It's the same as in other cases, just with new domain.

https://hub.esa-worldcereal.org/api/auth/callback

**Comment by mbabic84** [comment]
@kvantricht User login is mandatory, so, without that, application is not usable on production right now.

**Comment by kvantricht** [comment]
ok let's see if this can be addressed shortly

**Comment by soxofaan** [comment]
I raised the question to Cloudferro (which is in charge of the keycloak instance) to double check for https://hub.esa-worldcereal.org/api/auth/callback  I hope to get answer soon

**Comment by soxofaan** [comment]
I got some somewhat broken notification that the issue should be resolved, can you try again?

**Comment by mbabic84** [comment]
@soxofaan Hmm, still the same. Are the other params also the same as it was for the dev instance?

OID_CLIENT_ID: openeo-worldcereal-vdm
OID_IAM_ISSUER_URL: https://identity.dataspace.copernicus.eu/auth/realms/CDSE
OID_SELF_REDIRECT_URL: https://hub.esa-worldcereal.org/api/auth/callback

**Comment by soxofaan** [comment]
yes those look fine as far as I know

can you try again however, because there seems to be some mixup with notifications on when this was actually resolved

**Comment by mbabic84** [comment]
@soxofaan It works now. Thank you :)

**Comment by kvantricht** [comment]
@mbabic84 I was trying it and can indeed authenticate. After that however, my screen goes to black. Are you seeing that too?

![Image](https://github.com/user-attachments/assets/bdbf3adf-3ea3-464d-bef3-6b6824da0a25)

**Comment by soxofaan** [comment]
ah great, that's a relief

**Comment by mbabic84** [comment]
@kvantricht Unfortunately yes. Looking for solution now.

**Comment by mbabic84** [comment]
@kvantricht There seems to be some issue with certifactes on VM, which causing this issues in appliacation. It's blocking communication between application and its backend services on server side. Getting errors like

"Error: 588202D8507F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:", "wrong version number", "ERR_SSL_WRONG_VERSION_NUMBER" and when I try to run some system commands, which requires communication over ssl, for example "apt update" I'm getting erros like "Certificate verification failed: The certificate is NOT trusted. The signature in the certificate is invalid.  Could not handshake: Error in the certificate verification."

Not sure, what causing this. I have never seen errors like this on our own VMs. We do not use any certificates for internal communication between services.

**Comment by kvantricht** [comment]
which endpoints are you trying to connect to?

**Comment by kvantricht** [comment]
apparently all of the ones you need should be added to the SSL whitelist (VMs have become very strict)

**Comment by mbabic84** [comment]
@kvantricht I don't think it's what cousing this. I had to disable some internal security checks to make it work again. It made application a bit unstable, but it works for now. We are working on some more permanent solution.

**Comment by dirkdaems** [comment]
@mbabic84 wrt 'disabling some internal security checks': are you referring to security checks outside the VM?
If there is something we can do at the VM level to ease the integration, let us know.

**Comment by mbabic84** [comment]
@dirkdaems No, "Processing Hub" application has some internal logic, which checks if user is logged and if not, user is then redirected to login page. For some reason, this is not working on production VM. There is no issue on our VMs, where we are testing this. So, I'm not exactly sure why it is not working on production. I probably know how to solve this, but we will have refactor this logic and it will take some time.
